-- phpMyAdmin SQL Dump
-- version 4.0.9
-- http://www.phpmyadmin.net
--
-- Host: 127.0.0.1
-- Generation Time: Apr 13, 2014 at 11:10 PM
-- Server version: 5.6.14
-- PHP Version: 5.5.6

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `sif`
--

-- --------------------------------------------------------

--
-- Table structure for table `fall_2011`
--

CREATE TABLE IF NOT EXISTS `fall_2011` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `firstname` varchar(50) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `lastname` varchar(50) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `mem_year` varchar(15) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `mem_role` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `bio` longtext CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=17 ;

--
-- Dumping data for table `fall_2011`
--

INSERT INTO `fall_2011` (`id`, `firstname`, `lastname`, `mem_year`, `mem_role`, `bio`) VALUES
(1, 'Phil', 'Zhu', 'Fall 2011', 'Faculty Advisor', 'Phil Zhu is an Assistant Professor of Finance at the Eberhardt School of Business at the University of the Pacific. Dr. Zhu teaches courses in international finance as well as the introductory courses in financial management. His research focuses on cross-border mergers and acquisitions, corporate governance, and emerging market finance. He has published research articles in several journals including Journal of Corporate Finance, Journal of Business Research, Corporate Governance, Canadian Investment Review, and Advances in Quantitative Analysis of Finance and Accounting. Dr. Zhu is a recipient of the Barclay Global Investor Canada Research Award in 2006. Before joining the faculty at the University of the Pacific, Dr. Zhu taught at the Sprott School of Business, Carleton University. He also worked as a business analyst in a global management consulting firm in Canada. Dr. Zhu is a Chartered Financial Analyst (CFA).'),
(2, 'Faisal', 'Al Reshaid', 'Fall 2011', 'Chief Investment Officer & Consumer Discretionary Sector Analyst', 'Faisal Al Reshaid is a graduate of the Eberhardt School of Business at the University of the Pacific. Currently, Faisal is pursuing an MBA degree also from the University of the Pacific. Throughout the past 4 years, Faisal had the opportunity of working with multiple start-ups including the Powerhouse Science Center, on of the largest science center in North California, and the ST tournament, a community for gamers. At the University of the Pacific, Faisal was selected for the Student Investment Fund, a $1.5 million portfolio, and held multiple positions such as; Chief Investment Officer, Chief Administrator, and Senior Analyst. Faisal also lead research in multiple sectors; Technology, Consumer Staples, and Consumer Discretionary. Living with the mentality of “staying positive”, Faisal is able to accomplish his goals and influence others to overcome theirs. Classmates and professors usually convey Faisal as a strategic, positive, passionate, and influential student.'),
(3, 'Nataly', 'Teixeira', 'Fall 2011', 'Co-Chief Investment Officer & Materials Sector Analyst', 'Ms. Nataly Teixeira is majoring in B.S. Business Administration with concentration in Finance. Ms. Teixeira is currently a senior with an expected graduation date in May 2012. She possesses unique international knowledge, fluent in English, Russian, and Greek; Teixeira has had multiple multi-cultural interactions. She is experienced and knowledgeable of European and Eastern business practices. As Co-President of the Student investment Fund at The University of the Pacific, Ms. Teixeira, focuses on the materials sector. Her responsibilities include analyzing fund goals, determining direction and providing leadership to fellow members. Ms. Teixeira leverages her multiple years of experience in real estate investments, consulting and international relationship management to explore national and international patterns in order to direct successful investments.'),
(4, 'Rohan', 'Dixit', 'Fall 2011', 'Co-Portfolio Manager, Operations Manager, & Consumer Staples Analyst', 'Rohan is currently a senior in the Eberhardt School of Bsiness, working to obtain his B.S. in Business Administration with a concentration in finance, expecting to graduate in May of 2012. He currently holds the positions of Co-Portfolio Manager and Chief Operations Officer for the fund. During the 2011 summer, Rohan held an internship at Bloomberg L.P. in San Francisco in the Analytics and Financial Sales divisions. Rohan also worked as a Stock Broker intern at Scottrade in Modesto, CA during his junior year. Upon graduation, he hopes to work in financial services industry as a fixed income or equity analyst, while working to obtain his CFA Charter and MBA degree.'),
(5, 'Daniel', 'Idźkowski', 'Fall 2011', 'Co-Portfolio Manager, Chief Information Technology & Technology Sector Analyst', 'Danny is currently on his way to achieving a Bachelor of Science in Business Administration, concentrating in Information Systems Management.  Prior to SIF, Danny has undertaken various technical positions, one of which includes his current position as webmaster for the International Business Fraternity of Delta Sigma Pi at the University of the Pacific.  This past summer, Danny completed an internship performing data analysis and cross-reference mapping for Diversified Credit Investments LLC. At DCI, Danny had the unique opportunity to utilize his technical skills to collect and organize quantitative data which allowed him to better understand how financial data is used to develop models that accurately measure risk, identify credit mispricing, predict corporate defaults, and develop broadly diversified portfolios. After graduation, Danny hopes to continue his education by pursuing an MBA or CFA, and continue to apply his technical background to the field of investment management.'),
(6, 'Robert', 'Manassero', 'Fall 2011', 'Deputy Information Technology & Technology Sector Analyst', 'Robert Manassero is a senior at the University of the Pacific studying marketing and entrepreneurship as well as pursuing a minor in technology. Robert joined the student investment fund to get a first hand look on how investors think and approach investment strategies as well as learning valuable hands on profile management. Robert has held several positions in the international business fraternity Delta Sigma Pi. Robert is also the information technology manager for the campus radio and TV stations. During the summer, Robert interned at the Jackson Rancheria Casino and Hotel in the marketing department. During this internship, Robert learned the various aspects of casino marketing while receiving hands on experience with creating promotional campaigns, special event planning, graphic design production and database marketing. Robert hopes to pursue a career in the renewable energy industry.'),
(7, 'Hamza', 'Benjelloun', 'Fall 2011', 'Chief Economist & Industrial Sector Analyst', 'Hamza is an international student from Casablanca, Morocco. He has recently, graduated from the University of the Pacific, with a B.S. in Business Administration Concentration: Finance. Upon graduation, Hamza decided to continue his studies and pursue an MBA from the same university also with a concentration in Finance. Hamza has recently completed an Internship over the summer as a FOREX trader in one of the investment banks in Morocco. Hamza hopes to return home and start his career in the investment field as a portfolio manager.'),
(8, 'Navpreet', 'Kaur', 'Fall 2011', 'Chief Administrator, Deputy Economist, & Consumer Staples Sector Analyst', 'Preet is currently a junior at University of the Pacific, pursuing a B.S. in Finance (Eberhardt School of Business) and a B.A. in International Economics (College of the Pacific) and expected to graduate in May of 2013. This is Preet''s first semester in the Fund and currently holds the positions of Chief Administrator, Deputy Economist and Consumer Staples junior analyst. Preet has been actively involved on campus since her freshman year. She is currently the Chief Finance Officer for Kappa Alpha Theta- Phi Chapter, supervisor at Baun Fitness Center, while being an active member in Delta Sigma Pi and the Global Center for Social Entrepreneurship. Outside of school, Preet has been volunteering with the Make-A-Wish Foundation for the past five years and currently resides on the San Joaquin Advisory Board for the foundation. Preet has just returned from 3 months of interning and living in London and looks forward to exploring career opportunities in finance.'),
(9, 'Bethany', 'Quertermous', 'Fall 2011', 'Chief Accountant & Healthcare Sector Analyst', 'Bethany is a 2nd year MBA student at the University of the Pacific concentrating in Finance. She graduated from Pacific in May of 2010 with a B.S. in Business Administration with a minor in Mathematics. During her time at Pacific, she was a member of the Div. I Women''s Water Polo Team for four years, serving as captain her final year. Currently, she serves as a tutor in the athletic department as well as a graduate assistant in the business school. She''s had a few different internships including ones with California Cedar Products, Modesto Irrigation District, and the University''s Purchasing Department. After graduation, she plans to pursue a career as an actuary, blending her background in finance with her love of math. So far, she has passed one actuarial exam, the SOA/CAS Financial Mathematics/Exam 2, and plans to take the Probability Exam immediately after graduation in January 2012.'),
(10, 'Jonathan', 'Maes', 'Fall 2011', 'Deputy Accountant & Financial Sector Analyst', 'Jonathan is an exchange student from the Vrije Universite in Amsterdam who is currently in his senior year completing his B.S. in Business Administration with a concentration in finance. He grew up in the Netherlands and after graduating Jonathan attempts to do an MBA. Jonathan is planning to engage in a professional career as a trader in an international firm. Within the SIF Jonathan is a financial sector analyst.'),
(11, 'Julia', 'Hansen', 'Fall 2011', 'Deputy Accountant & Financial Sector Analyst', 'Julia Hansen is an international student from Hamburg, Germany. She is currently a senior, completing a BS in Business Administration with a double concentration in International Business and Finance. In the investment fund, Julia is a financial sector analyst as well as the deputy accountant. Julia is also a member of the Pacific Division I Women''s Tennis team and was named First Team Doubles as well as Second Team Singles in 2011. After graduating from Pacific, Julia is planning to pursue an MBA at either the University of the Pacific or Germany.'),
(12, 'Ann', 'Tran', 'Fall 2011', 'Outreach Coordinator & Utility Sector Analyst', 'As an undergraduate student, Ann Tran is on track to receiving her B.A. in Business Administration (concentration Finance) in three years. She received the Powell Scholarship, Pacific''s highest merit scholarship, upon entering Pacific and is part of the Legal Scholars Program, an accelerated honors program in conjunction with Pacific McGeorge School of Law. She is an active member of the community service fraternity Alpha Phi Omega and is currently doing undergraduate research with a professor. In the future, Ann hopes to receive a joint MBA/ J.D. degree.'),
(13, 'Jory', 'Cook', 'Fall 2011', 'Risk Management Officer, Fixed Income, & International Fixed Income Sector Analyst', 'Jory Cook is currently pursuing his JD/MBA at the University of the Pacific. He received his BA in World Religions from the University of Bridgeport in Connecticut, and taught English as a Second Language in Japan and Korea before returning to California. Jory grew up in Japan, California and Costa Rica, and has worked in Japan, Korea, and Costa Rica. After graduating from Pacific, Jory hopes to work as internal legal counsel for an international investment firm.'),
(14, 'Russell', 'Schwartz', 'Fall 2011', 'Deputy Risk Management Officer & Industrial Sector Analyst', 'Russell is an MBA candidate at the University of the Pacific concentrating in Finance. In SIF, Russell is presently the Deputy Risk Management Officer and industrial sector analyst. He graduated in May 2010 from California State University Fullerton with a B.A. in Business Administration with concentrations in Operations Research and Risk Management. Russell recently completed a summer internship at the Federal Deposit Insurance Corporation (FDIC). After graduation, he will return to the FDIC to begin the process of becoming a commissioned bank examiner, which he hopes to complete in three years.'),
(15, 'Ivan', 'Yeo Shi Sheng', 'Fall 2011', 'Financial and Energy Sector Analyst', 'Ivan Yeo is currently a Junior, on his way to achieving a B.S. in Business Administration with a concentration in Finance. He is currently the energy sector analyst within the investment fund. Ivan became passionate about Finance at the age of 16 when his dad introduced him to the stock market. Ever since then, Ivan has developed his knowledge in financial markets and is currently trading his own portfolio in Stocks. FX and Index Futures. This past summer, Ivan did a financial internship with ABN AMRO in Singapore as a Risk Management Trainee. His experience in Singapore helped to develop his love for finance and further amplified his belief that money management is one of the most important factor in trading. When he graduates, he hopes to find a position as a Proprietary Trader and eventually start his own hedge fund.'),
(16, 'Antonin', 'Chiberches', 'Fall 2011', 'International Equity & Energy Sector Analyst', 'Antonin is an exchange student from Institut d''Administration des Entreprises in Toulouse. He has been studying economics for two years and is now a senior completing a BS in business administration with a concentration in Finance. He is planning on going back to France to attempt a Masters in Finance after graduation. He did a 3 month training period in a French auditing company. Living with a competitive mentality, Antonin plays ice hockey and does skiing in competition. He grew up in France and Australia and is wishing to work in portfolio management/Trading rooms.');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
