-- phpMyAdmin SQL Dump
-- version 4.0.9
-- http://www.phpmyadmin.net
--
-- Host: 127.0.0.1
-- Generation Time: Apr 13, 2014 at 11:11 PM
-- Server version: 5.6.14
-- PHP Version: 5.5.6

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `sif`
--

-- --------------------------------------------------------

--
-- Table structure for table `spring_2013`
--

CREATE TABLE IF NOT EXISTS `spring_2013` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `firstname` varchar(50) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `lastname` varchar(50) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `mem_year` varchar(15) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `mem_role` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `bio` longtext CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=21 ;

--
-- Dumping data for table `spring_2013`
--

INSERT INTO `spring_2013` (`id`, `firstname`, `lastname`, `mem_year`, `mem_role`, `bio`) VALUES
(1, 'Phil', 'Zhu', 'Spring 2013', 'Faculty Advisor', 'Phil Zhu is an Assistant Professor of Finance at the Eberhardt School of Business at the University of the Pacific. Dr. Zhu teaches courses in international finance as well as the introductory courses in financial management. His research focuses on cross-border mergers and acquisitions, corporate governance, and emerging market finance. He has published research articles in several journals including Journal of Corporate Finance, Journal of Business Research, Corporate Governance, Canadian Investment Review, and Advances in Quantitative Analysis of Finance and Accounting. Dr. Zhu is a recipient of the Barclay Global Investor Canada Research Award in 2006. Before joining the faculty at the University of the Pacific, Dr. Zhu taught at the Sprott School of Business, Carleton University. He also worked as a business analyst in a global management consulting firm in Canada. Dr. Zhu is a Chartered Financial Analyst (CFA).'),
(2, 'Katrina', 'Fischer', 'Spring 2013', 'Healthcare Sector Analyst', 'Katrina Fischer earned her bachelor’s degree from UCLA majoring in Microbiology, Immunology and Molecular Genetics. She is currently pursuing her MBA degree from the University of the Pacific and is a 4th year medical student at UCLA. She is participating in SIF as an analyst in the healthcare sector in order to gain exposure to a side of the medical field not typically experienced by medical students. In addition to school she is interning at a local health insurance plan and conducting research in health professional growth patterns. After graduation she will complete medical school and pursue a residency in Internal Medicine.'),
(3, 'Erick', 'Tran ', 'Spring 2013', 'Portfolio Manager & Technology Sector Analyst', 'Erick Tran is a senior at the University of the Pacific, where he is working on obtaining his B.S. in Business Administration with a concentration in Accounting. Throughout his college experience, Erick has worked hard to excel in both his academics and social life, in order to cultivate himself into a well-rounded, experienced individual. Erick is part of the International Business Fraternity, Delta Sigma Pi, as well as the Event Coordinator for the Accounting, Finance and Management Honorary Society, Beta Alpha Psi. In order to give back to his campus, Erick is an Accounting tutor for the Success program at the University of the Pacific. Upon graduation, Erick plans on working towards obtaining his certification as a CPA as well as his Masters of Accountancy (MAcc).'),
(4, 'Jeff', 'Earl', 'Spring 2013', 'Chief Operations Manager & Consumer Staples Sector Analyst', 'Jeff is a senior at the Eberhardt School of Business currently pursuing a Bachelor of Sciences degree in Business Administration with a concentration in finance as well as a minor in economics. He is currently a senior analyst for the Consumer Staples sector. Jeff expects to graduate in December of 2013 and is eager to gain skills in stock and bond valuation, Bloomberg and Capital IQ research, and portfolio management. He worked as a golf professional for 15 years at Stockton G&CC and Valley Hi G&CC, where he taught extensively and ran daily golf shop operations. He is currently a member of the PGA of America. After graduation, Jeff plans to work on his CFA charter and ultimately work as an equity or fixed income analyst.'),
(5, 'Matthew', 'Pearson', 'Spring 2013', 'Chief Economist & Financial Sector Analyst', 'Matthew Pearson is a senior at the University of the Pacific working toward Bachelors of Science in Business Administration concentrating in Finance while minoring in Economics and International Studies. He currently holds the positions within the fund of Chief Economist and serves as a Financial Sector Analyst. Matt has worked in various leadership roles on campus including a building manager at the Derosa University Center along with being a part of the professional business fraternity Delta Sigma Pi. He is a member of the Legal Scholars Program and has interned in the non-profit sector.'),
(6, 'Shayne', 'Brown', 'Spring 2013', 'Chief Marketing Officer & Energy Sector Analyst', 'Shayne Brown is a senior and pursuing a degree in Economics. This is his second semester in the Student Investment Fund, holding the positions Chief Marketing/Recruiting Officer and Energy Sector Analyst. He wants to work for a financial advising firm or investment bank and possibly open up his own firm in the future.'),
(7, 'Tim', 'Ye', 'Spring 2013', 'Risk Management Officer & Technology Sector Analyst', 'Tim is a junior at the University of the Pacific, working towards a BA in Business Administration with a concentration in Finance and MIS. This is his second semester in SIF and in the future he hopes to work in the high tech industry. In the past year, he has worked for Facebook under the Data Center department, helping them do post construction cost analysis. After graduation, he hopes to work in the Bay Area for a high tech firm as a business analyst.'),
(8, 'Rita', 'Velazquez', 'Spring 2013', 'Chief Accountant & Consumer Discretionary Analyst', 'Rita Velazquez is currently a senior, on her way to achieving a B.S. degree in Business Administration with a concentration in Accounting. She is currently the Consumer Discretionary sector analyst within the investment fund as well as our accounting representative. Other duties include accounting procedures. Rita joined SIF because of her strong interest in the stock market and the desire to learn about finance. Working in a business environment as a bookkeeper encouraged her to pursue a career in Business Administration. After graduation she wants to earn a Masters in accounting and soon after, work at an accounting firm or a finance company to gain valuable experience and knowledge. She hopes to one day own her business.'),
(9, 'Joel', 'Stice', 'Spring 2013', 'Co-Operations Manager & Technology Sector Analyst', 'Joel is a senior working towards the completion of his undergraduate studies at the University of the Pacific. He has chosen to pursue a degree in Business Administration with a concentration in Finance. Joel has spent time in the housing sector as a loan officer as well as working for Apple Inc. as a specialist. As a member of the Student Investment Fund, he hopes to obtain an in-depth knowledge about stock valuation and industry analysis. Upon graduation, he plans on working towards his CFA charter and furthering his investing experience in the financial industry.'),
(10, 'Shree', 'Sharma', 'Spring 2013', 'Consumer Staples Sector Analyst', 'Shree is a graduating Third-Year from the Eberhardt School of Business. She chose to join the Student Investment Fund to gain first-hand knowledge about the financial industry. As a Human Resource concentration, she loves applying what she learns in her HR courses to other classes so she is excited to see what opportunities lie ahead while working with the fund.'),
(11, 'Kendall', 'Burke', 'Spring 2013', 'Materials Sector Analyst', 'Kendall is in her last semester of undergraduate school at Pacific and will be graduating this semester with her Bachelors of Science degree in Finance. She chose to join SIF to gain a hands-on experience in the financial world. She is grateful for this opportunity and looking forward to applying all knowledge learned throughout the semester towards her future career.'),
(12, 'Erik', 'Cederwall', 'Spring 2013', 'Financial Sector Analyst', 'Erik Cederwall is currently a junior, pursuing a Bachelor’s Degree in Economics at the University of the Pacific. Erik is an international student from Stockholm, Sweden, and a member of the UOP men’s tennis team. Erik is grateful for the opportunity to be involved with a high-impact group as the Eberhardt Student Investment Fund and to further immerse with the field of investing. In addition to his passion for tennis and investing, Erik is fascinated by social entrepreneurship and enjoys traveling.'),
(13, 'Alexander', 'Schlabach', 'Spring 2013', 'Fixed Income Analyst', 'Alex is a junior at the Eberhardt School of Business currently pursuing a Bachelor of Sciences degree in Business Administration with a concentration in finance as well as accounting. He is also pursuing a Masters of Accounting. He is expected to graduate with both degrees in spring 2015. He is currently an analyst for the Fixed Income sector of the SIF portfolio. He is eager to gain experience in stock and bond valuation, portfolio management, derivative analysis, Bloomberg and Capital IQ navigation. After graduation Alex plans to pursue his CPA and CFA charter and ultimately work as an analyst for a portfolio management firm.'),
(14, 'Andy', 'Le', 'Spring 2013', 'Industrial Sector Analyst', 'Andy Le is an international student from Vietnam. He has been living in the US for almost 5 years and spent all 4 years of college in Orange County, Southern California. He went to Cypress College for 2 years and then transferred to Chapman University to finish his undergraduate degree. He graduated from Chapman with a bachelor’s degree in business administration, concentration in finance. Currently, Andy is an MBA student at UOP with a concentration in finance, and he is thinking of choosing entrepreneurship as a second concentration. He is also working as a research assistant for professor Wenjing Ouyang. Andy will finish his MBA program this December and hopefully will be able to find a job related to his major in the U.S.'),
(15, 'Tyler', 'Vik', 'Spring 2013', 'Fixed Income Analyst', 'Tyler is currently a Senior at the University of the Pacific and will be receiving his Bachelors of Science degree in Economics. This is his first semester in SIF, and he currently holds the positions Fixed Income Analyst and Economist. After interning in the Wealth Management division of UBS, Tyler has decided to pursue a career in this field upon graduation.'),
(16, 'Terrin', 'Clark', 'Spring 2013', 'Energy Sector Analyst', ''),
(17, 'Samarth', 'Karia', 'Spring 2013', 'Healthcare Sector Analyst', 'Sam Karia a senior at University of the Pacific, pursuing a degree in Business Administration, with a concentration in finance. In addition to my curriculum, I serve as V.P. of Brotherhood for Delta Sigma Pi, a professional business fraternity, as well as a Founding Father of Beta Theta Pi. I have had two internships in the financial industry, one at Modern Bank in New York and the other at Barclays in Torino, Italy. In regards to the Student Investment Fund, I am in charge of outreach and am a junior analyst for the healthcare sector. After college, I am looking to obtain a position in the investments industry preferably on the east coast.'),
(18, 'Sueno', 'Li', 'Spring 2013', 'Utilities Sector Analyst', 'Sueno is an international student from Zhengzhou, Henan, China. She earned her bachelors of economics degree from Zhengzhou University, and on August 2012 came to America to pursue her MBA degree from the Eberhardt School of Business. She is fluent in Chinese and extremely familiar with the Chinese culture. This is her first semester in SIF and she is in charge of the Utilities Sector. She hopes in the future this experience will be beneficial and can be incorporated into her work.'),
(19, 'Patrick', 'Daley', 'Spring 2013', 'Chief Investment Officer & Industrials Sector Analyst', 'Patrick Daley is a senior at the University of the Pacific, and will be receiving his bachelor’s degree from the Eberhardt School of Business with a concentration in finance. This is Patrick’s second semester in SIF, but his interest in the financial markets dates back to his freshman year of high school when he played stock market simulations for the first time. His ability to tune out all of the noise and see situations for the way they really are is what makes Patrick a great analyst. After college, he plans to study for the CFA exam while he looks for a job in the financial industry to get some more experience.'),
(20, 'Leslie', 'Vaughan', 'Spring 2013', 'Industrials Sector Analyst', 'Leslie Vaughan is a visiting Accounting Instructor here at the University of the Pacific. She is a licensed CPA and CMA. Leslie is currently a junior analyst for the Healthcare sector. Her interests lie in how the economy affects the stock market and best practices for diversified investing. She hopes to sit for the CFA exam in the future.');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
