// Generated by CoffeeScript 1.7.1
(function() {
  var Company, Sector, db;

  db = require("db");

  Sector = db.models.Sector;

  Company = (function() {
    function Company() {}

    Company.path = "/company";

    Company.route_name = "company_";

    Company.prototype.index = {
      "/": function() {
        return {
          get: function() {
            return this.res.redirect(this.url_for("company_about"));
          }
        };
      }
    };

    Company.prototype.about = {
      "/about": function() {
        return {
          get: function() {
            return Sector.select().then((function(_this) {
              return function(sectors) {
                return _this.res.render("company/about", {
                  title: "Company | ESB SIF",
                  navbar: "company",
                  sectors: sectors
                });
              };
            })(this));
          }
        };
      }
    };

    Company.prototype.team = {
      "/team": function() {
        return {
          get: function() {
            return this.res.render("company/team", {
              title: "Company",
              navbar: "company"
            });
          }
        };
      }
    };

    Company.prototype["/team/fall-2013"] = function() {
      return {
        get: function() {
          return this.res.render("company/fall-2013", {
            title: "Fall 2013",
            navbar: "company"
          });
        }
      };
    };

    Company.prototype["/team/fall-2013/:member"] = function() {
      return {
        get: function() {
          return this.res.render("company/member", {
            title: "Member!",
            navbar: "company",
            name: ""
          });
        }
      };
    };

    return Company;

  })();

  module.exports = Company;

}).call(this);
