// Generated by CoffeeScript 1.7.1
(function() {
  var Portfolio, Sector, db;

  db = require("db");

  Sector = db.models.Sector;

  Portfolio = (function() {
    function Portfolio() {}

    Portfolio.path = "/portfolio";

    Portfolio.route_name = "portfolio_";

    Portfolio.prototype.index = {
      "/": function() {
        return {
          get: function() {
            return this.res.redirect(this.url_for("portfolio_sectors"));
          }
        };
      }
    };

    Portfolio.prototype.sectors = {
      "/sectors": function() {
        return {
          get: function() {
            return Sector.select().then((function(_this) {
              return function(sectors) {
                return _this.res.render("portfolio/sectors", {
                  title: "Portfolio | ESB SIF",
                  navbar: "portfolio",
                  sectors: sectors
                });
              };
            })(this));
          }
        };
      }
    };

    Portfolio.prototype.sector = {
      "/sectors/:abbrv": function() {
        return {
          get: function() {
            var abbrv;
            abbrv = this.params.abbrv;
            return Sector.find({
              abbrv: abbrv
            }).then((function(_this) {
              return function(sector) {
                if (!sector) {
                  _this.res.redirect(_this.url_for("portfolio_sectors"));
                }
                return _this.res.render("portfolio/sector", {
                  title: "" + (abbrv.toUpperCase()) + " | ESB SIF",
                  navbar: "portfolio",
                  project: sector
                });
              };
            })(this), function(err) {
              console.log("stupid erro", err);
              return this.res.redirect(this.url_for("portfolio_sectors"));
            });
          }
        };
      }
    };

    return Portfolio;

  })();

  module.exports = Portfolio;

}).call(this);
