// Generated by CoffeeScript 1.7.1
(function() {
  var Users, bcrypt, validator;

  validator = require("validator");

  bcrypt = require("bcrypt");

  Users = (function() {
    function Users() {}

    Users.path = "/users";

    Users.route_name = "users_";

    Users.prototype.index = {
      "/": function() {
        return {
          post: function() {
            var password, username;
            username = this.params.username;
            password = this.params.password;
            if (!validator.isEmail(username)) {
              this.res.json({
                error: "Not valid email"
              });
            }
            return bcrypt.genSalt(10, (function(_this) {
              return function(err, salt) {
                return bcrypt.hash(password, salt, function(err, hash) {
                  if (err) {
                    throw err;
                  }
                  return _this.res.json({
                    "success": "success"
                  });
                });
              };
            })(this));
          }
        };
      }
    };

    return Users;

  })();

  module.exports = Users;

}).call(this);
