// Generated by CoffeeScript 1.7.1
(function() {
  var Model, Team, db, schema, types,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  db = require("db");

  Model = db.Model;

  schema = db.schema;

  types = schema.types;

  schema.create_table("teams", [
    {
      name: "id",
      type: types.serial
    }, {
      name: "year",
      type: types.text
    }, "PRIMARY KEY (id)"
  ]).then(function() {
    return schema.create_index("teams", "year", {
      unique: true
    });
  });

  Team = (function(_super) {
    __extends(Team, _super);

    function Team() {
      return Team.__super__.constructor.apply(this, arguments);
    }

    Team.table = "teams";

    return Team;

  })(Model);

  module.exports = Team;

}).call(this);
