// Generated by CoffeeScript 1.7.1
(function() {
  var Model, User, db, schema, types,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  db = require("db");

  Model = db.Model;

  schema = db.schema;

  types = schema.types;

  schema.create_table("users", [
    {
      name: "id",
      type: types.serial
    }, {
      name: "img",
      type: types.text
    }, {
      name: "bio",
      type: types.text
    }, {
      name: "email",
      type: types.text
    }, {
      name: "title",
      type: types.text
    }, {
      name: "firstname",
      type: types.text
    }, {
      name: "lastname",
      type: types.text
    }, "PRIMARY KEY (id)"
  ]).then((function() {
    return schema.create_index("users", "email", {
      unique: true
    });
  }), console.log);

  User = (function(_super) {
    __extends(User, _super);

    function User() {
      return User.__super__.constructor.apply(this, arguments);
    }

    User.table = "users";

    return User;

  })(Model);

  module.exports = User;

}).call(this);
